# Generated by Django 2.2.24 on 2025-02-06 12:29

from django.db import migrations


def set_new_building(apps, schema_editor):
    flat = apps.get_model('property', 'Flat')
    flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    flat.objects.filter(construction_year__lt=2015).update(new_building=False)   


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building),
    ]
