# Generated by Django 4.2.19 on 2025-02-06 15:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_pure_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True, verbose_name='Наличие балкона'),
        ),
    ]
