# Generated by Django 4.2.19 on 2025-02-06 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_flat_owners_pure_phonenumber_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
