# Generated by Django 4.2.19 on 2025-02-06 15:52

from django.db import migrations
from phonenumbers import parse, is_valid_number, PhoneNumberFormat, format_number


def set_pure_phone_numbeer(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.iterator():
        if is_valid_number(parse(flat.owners_phonenumber, 'RU')):
            phone_number = flat.owners_phonenumber
            parsed_number = parse(phone_number, "RU")
            flat.owners_pure_phonenumber = format_number(
                parsed_number, PhoneNumberFormat.E164)
        else:
            flat.owners_pure_phonenumber = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_flat_liked'),
    ]

    operations = [
        migrations.RunPython(set_pure_phone_numbeer),
    ]
