# Generated by Django 4.2.19 on 2025-02-07 10:44

from django.db import migrations


def create_existing_owners(apps, schema_editor):
    Flats_model = apps.get_model('property', 'Flat')
    Owner_model = apps.get_model('property', 'Owner')
    for flat in Flats_model.objects.all():
        owner, _ = Owner_model.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owners_pure_phonenumber
        )
        owner.owned_flats.add(flat.id)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(create_existing_owners)
    ]
