# Generated by Django 4.2.19 on 2025-02-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_liked_remove_owner_owned_flats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.flat', verbose_name='Кваритра, на которую жаловались'),
        ),
    ]
